
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class SearchTrain extends javax.swing.JFrame {

    /**
     * Creates new form SearchTrain
     */
    public SearchTrain() {
        initComponents();
        Connect();
        loadsplace( );
        loadendplace( );
        loaddate();
    }

    Connection connect;
  PreparedStatement pst;
    ResultSet rst;
    
    public void Connect()  {
    
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                connect = DriverManager.getConnection("jdbc:mysql://localhost/metrobangla","root","");
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    public void loadsplace()  {
      
      
        
        try {
            pst=connect.prepareStatement("SELECT tfrom FROM trains");
            rst=pst.executeQuery();
            txtsplace.removeAllItems();
            while(rst.next()){
                txtsplace.addItem(rst.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SearchTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
  }
  public void loadendplace()  {
        
        try {
            pst=connect.prepareStatement("SELECT tto FROM trains");
            rst=pst.executeQuery();
            txtendp.removeAllItems();
            while(rst.next()){
                txtendp.addItem(rst.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SearchTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      
      
  }
  public void loaddate()  {
        
        try {
            pst=connect.prepareStatement("SELECT date FROM trains");
            rst=pst.executeQuery();
            txtdate.removeAllItems();
            while(rst.next()){
                txtdate.addItem(rst.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SearchTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      
      
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfind = new javax.swing.JButton();
        txtclear = new javax.swing.JButton();
        txtback = new javax.swing.JButton();
        txtsplace = new javax.swing.JComboBox<>();
        txtendp = new javax.swing.JComboBox<>();
        txtdate = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txttname = new javax.swing.JTextField();
        txtdepart = new javax.swing.JTextField();
        txttno = new javax.swing.JTextField();
        txtreach = new javax.swing.JTextField();
        txtgen = new javax.swing.JTextField();
        txtac1 = new javax.swing.JTextField();
        txtac2 = new javax.swing.JTextField();
        txtfc = new javax.swing.JTextField();
        txtslp = new javax.swing.JTextField();
        txtreaserve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 204));
        jLabel7.setText("Departs:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 351, -1, 34));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 204));
        jLabel8.setText("Reaches:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 407, -1, 36));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 204));
        jLabel9.setText("Train NO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 238, -1, 32));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 204));
        jLabel10.setText("AC1:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 266, -1, 30));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 204));
        jLabel11.setText("AC2:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 314, -1, 31));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 204));
        jLabel12.setText("Train Name:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 303, -1, 30));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setText("SLP:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 51, 31));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 204));
        jLabel15.setText("Gen:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 464, 53, 33));

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 204));
        jLabel16.setText("FC:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 371, 36, 30));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 3, true));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("From:");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("To:");

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setText("YYYY-MM-DD");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Travel Date:");

        txtfind.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        txtfind.setForeground(new java.awt.Color(153, 0, 102));
        txtfind.setIcon(new javax.swing.ImageIcon("E:\\2nd1st\\Metro-Rail\\src\\images\\train-24.png")); // NOI18N
        txtfind.setText("Find Train");
        txtfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfindActionPerformed(evt);
            }
        });

        txtclear.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        txtclear.setForeground(new java.awt.Color(102, 0, 102));
        txtclear.setIcon(new javax.swing.ImageIcon("E:\\2nd1st\\Metro-Rail\\src\\images\\x-mark-2-24.png")); // NOI18N
        txtclear.setText("Clear Fields");
        txtclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclearActionPerformed(evt);
            }
        });

        txtback.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtback.setForeground(new java.awt.Color(0, 0, 153));
        txtback.setIcon(new javax.swing.ImageIcon("E:\\2nd1st\\Metro-Rail\\src\\images\\arrow-81-24.png")); // NOI18N
        txtback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbackActionPerformed(evt);
            }
        });

        txtsplace.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtsplace.setForeground(new java.awt.Color(153, 0, 153));

        txtendp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtendp.setForeground(new java.awt.Color(153, 0, 153));

        txtdate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtdate.setForeground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsplace, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtendp, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtback))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(txtfind)
                        .addGap(41, 41, 41)
                        .addComponent(txtclear)
                        .addGap(0, 107, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsplace, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtendp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtback))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfind)
                            .addComponent(txtclear))
                        .addContainerGap())))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 980, 153));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("METRO-Ticket");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 51));

        txttname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txttname.setForeground(new java.awt.Color(153, 0, 153));
        txttname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttnameActionPerformed(evt);
            }
        });
        jPanel1.add(txttname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 298, 174, 35));

        txtdepart.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtdepart.setForeground(new java.awt.Color(153, 0, 153));
        txtdepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepartActionPerformed(evt);
            }
        });
        jPanel1.add(txtdepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 354, 174, 30));

        txttno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txttno.setForeground(new java.awt.Color(102, 0, 102));
        txttno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttnoActionPerformed(evt);
            }
        });
        jPanel1.add(txttno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 238, 174, 34));

        txtreach.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtreach.setForeground(new java.awt.Color(153, 0, 153));
        txtreach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreachActionPerformed(evt);
            }
        });
        jPanel1.add(txtreach, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 408, 174, 35));

        txtgen.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtgen.setForeground(new java.awt.Color(153, 0, 153));
        txtgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenActionPerformed(evt);
            }
        });
        jPanel1.add(txtgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 464, 174, 33));

        txtac1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtac1.setForeground(new java.awt.Color(153, 0, 153));
        txtac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtac1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 156, 32));

        txtac2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtac2.setForeground(new java.awt.Color(153, 0, 153));
        txtac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtac2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 156, 32));

        txtfc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtfc.setForeground(new java.awt.Color(204, 0, 204));
        txtfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfcActionPerformed(evt);
            }
        });
        jPanel1.add(txtfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 156, 30));

        txtslp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        txtslp.setForeground(new java.awt.Color(153, 0, 153));
        txtslp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtslpActionPerformed(evt);
            }
        });
        jPanel1.add(txtslp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 156, 30));

        txtreaserve.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        txtreaserve.setForeground(new java.awt.Color(0, 0, 204));
        txtreaserve.setIcon(new javax.swing.ImageIcon("E:\\2nd1st\\Metro-Rail\\src\\images\\seat-32.png")); // NOI18N
        txtreaserve.setText("Reserve seat");
        txtreaserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreaserveActionPerformed(evt);
            }
        });
        jPanel1.add(txtreaserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 515, -1, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfindActionPerformed
         String splace=txtsplace.getSelectedItem().toString();
            String eplace=txtendp.getSelectedItem().toString();
            String date=txtdate.getSelectedItem().toString();
        try
        {

             pst=connect.prepareStatement("select* from trains where tfrom=? and tto=? and date=?");
            
           
            
            pst.setString(1, splace);
            pst.setString(2, eplace);
            pst.setString(3, date);
            rst=pst.executeQuery();
        if(rst.next() == true)
        {
             txttno.setText(rst.getString(1));
            txttname.setText(rst.getString(2));
            txtdepart.setText(rst.getString(5));
            txtreach.setText(rst.getString(6));
            txtgen.setText(rst.getString(7));
            txtac1.setText(rst.getString(8));
            txtac2.setText(rst.getString(9));
            txtfc.setText(rst.getString(10));
            txtslp.setText(rst.getString(11));
                
}
        else
        {
           // txtendp.setText(rst.getString(3));
            JOptionPane.showMessageDialog(null," No Such Records Invalid !!!!!");
     
         
        // txtdate.setText("");
         txttno.setText("");
            txttname.setText("");
            txtdepart.setText("");
            txtreach.setText("");
            txtgen.setText("");
            txtac1.setText("");
            txtac2.setText("");
            txtfc.setText("");
            txtslp.setText("");
      
      txtendp.requestFocusInWindow();
      txtdate.requestFocusInWindow();
           
             }
        
        //        String sql="select * from trains where tto='"+eplace+"' and date='"+txtdate.getText()+"'";
//      
//        Statement s=connect.createStatement();
//         pst.setString(2, eplace);
//        rst=s.executeQuery(sql);
        
//        if(rst.next() == false)
//        {
//                JOptionPane.showMessageDialog(null," No Such Records Invalid !!!!!");
//     
//         
//         txtdate.setText("");
//         
//      
//      txtendp.requestFocusInWindow();
//      txtdate.requestFocusInWindow();
//}
//        else
//        {
//           // txtendp.setString(rst.getString(3));
//            
//            txttno.setText(rst.getString(1));
//            txttname.setText(rst.getString(2));
//            txtdepart.setText(rst.getString(5));
//            txtreach.setText(rst.getString(6));
//            txtgen.setText(rst.getString(7));
//            txtac1.setText(rst.getString(8));
//            txtac2.setText(rst.getString(9));
//            txtfc.setText(rst.getString(10));
//            txtslp.setText(rst.getString(11));
//             }
//        
      }
      catch(Exception ee)
      {
          
      }
    }//GEN-LAST:event_txtfindActionPerformed

    private void txtclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclearActionPerformed
        this.setVisible(false);
        new SearchTrain().setVisible(true);
    }//GEN-LAST:event_txtclearActionPerformed

    private void txtbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbackActionPerformed
        this.setVisible(false);
        new reservation().setVisible(true);
    }//GEN-LAST:event_txtbackActionPerformed

    private void txttnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttnameActionPerformed

    private void txtdepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepartActionPerformed

    private void txttnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttnoActionPerformed

    private void txtreachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreachActionPerformed

    private void txtgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenActionPerformed

    private void txtac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtac1ActionPerformed

    private void txtac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtac2ActionPerformed

    private void txtfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfcActionPerformed

    private void txtslpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtslpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtslpActionPerformed

    private void txtreaserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreaserveActionPerformed
        this.setVisible(false);
        new Train().setVisible(true);
    }//GEN-LAST:event_txtreaserveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchTrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtac1;
    private javax.swing.JTextField txtac2;
    private javax.swing.JButton txtback;
    private javax.swing.JButton txtclear;
    private javax.swing.JComboBox<String> txtdate;
    private javax.swing.JTextField txtdepart;
    private javax.swing.JComboBox<String> txtendp;
    private javax.swing.JTextField txtfc;
    private javax.swing.JButton txtfind;
    private javax.swing.JTextField txtgen;
    private javax.swing.JTextField txtreach;
    private javax.swing.JButton txtreaserve;
    private javax.swing.JTextField txtslp;
    private javax.swing.JComboBox<String> txtsplace;
    private javax.swing.JTextField txttname;
    private javax.swing.JTextField txttno;
    // End of variables declaration//GEN-END:variables
}
